### ISSUE TITLE
[Suggestion] Read only and Read Write databases.

### ISSUE THREAD

**Issue by Lion4K** [root670/CheatDevicePS2#11]
Like, add an option so that you can have a compressed database (zip or cdb) and an empty txt to write only changes to it.

Lets say you add, or change a game from the UI it instead of copying all cheats from the compressed database and changing the ini to use that, it will just write to the secondary database, keeping a compressed copy and just the few bytes from the new information on the alternative database, keeping that too small.

This occurred to me when I tried adding a game to my list over the UI and when it saved, it actually dumped the whole CDB making a 7MB file inside the MC0, and also left the now outdated cdb behind.

So yeah, to sum up it would simply save to a cheats.txt and load from cheat.cdb and cheats.txt

Sorry if this is a bad place for adding suggestions.

**Comment by Lion4K** [comment]
Just to add, it would be pretty much like commercial cheats does, they don't dump all their databases to the memory card, only the newest additions, and references of the ones to be hidden (when you delete).

Just remembered that.

**Comment by root670** [comment]
This is a great idea. I've begun implementing support for a read-only and read/write database and should have it completed soon.

**Comment by root670** [comment]
I've completed the implementation supporting a read-only and read-write database. See #14
