### ISSUE TITLE
Code deletion bug - Incorrect code is deleted

### ISSUE THREAD

**Issue by ghost** [root670/CheatDevicePS2#12]
I have code entries which are several lines long like this:

Codename
20000001 00000000
20000002 00000000
20000003 00000000
...
...
20000010 00000000

Suppose I choose to delete "20000003 00000000". The next time cheat device is booted, it will appear that "20000010 00000000" has incorrectly been deleted instead .

**Comment by root670** [comment]
Thanks for reporting this bug! Looks like I made a silly mistake in `cheatsDeleteCodeLine()`.
