### ISSUE TITLE
can't load database in hdd or smb

### ISSUE THREAD

**Issue by hardlevel** [root670/CheatDevicePS2#17]
when I try to use cheatdevice over smb or hdd mode, the program can`t load the database, sometimes it happen with external hdd too, working only in thumbstick, there`s something to do or it`s a know bug? any chances to check this?

**Comment by root670** [comment]
Cheat Device doesn’t have the IOP modules necessary to access the hard drive or an SMB filesystem. I had tried adding support for the hard drive before but had issues with it breaking printf, making debugging difficult with my setup. I’d like to look into this again though as I know booting ELFs from the hard drive is a desirable feature.

For the time being Cheat Device can only be run from a flash drive or memory card.
