### ISSUE TITLE
CheatDevicePS2 using OPL?

### ISSUE THREAD

**Issue by Dokman** [root670/CheatDevicePS2#19]
So when i use it any cheat isn't working i am using a european ps2 and PAL games and i don't know if your latest DB is using PAL games so what can be the problem? i am using OPL because i am launching my backuped games with a HDD

PS: i am using your tool in a USB with OPL in the usb but the games are in the HDD

**Comment by root670** [comment]
The bundled cheat database is for NTSC-region games only. To use cheats with PAL-region games, you'll need to create a new database containing cheats for PAL games.

This is a good resource for PAL cheats: https://www.ultimate-cheatz.de/codebase/

You can use codes from that website as long as they are decrypted using a tool like OmniConvert.
