### ISSUE TITLE
Getting Black Screen

### ISSUE THREAD

**Issue by Dokman** [root670/CheatDevicePS2#2]
Hello with your 1.2.1 release i have a black window with FreeMCBoot 1.94 what can i do?

**Comment by root670** [comment]
Does the "Loading..." text appear? Any error messages displaying?

**Comment by Dokman** [comment]
Nothing only balck screen

**Comment by root670** [comment]
Looks like it works in PCSX2 but not on a real console. The uncompressed version does however work on PCSX2 and consoles so ps2-packer seems to be the root of the issue. The compressed version of 302b737 (the commit just before v1.2.1) also works, yet the final commit in v1.2.1 introduced very minor changes that shouldn't effect initialization.

**Comment by Dokman** [comment]
i don't know hahahaha i only know that doesn't show anything my screen.
only a black screen

**Comment by Dokman** [comment]
@root670 Any news?

**Comment by Dokman** [comment]
can be closed with the newest attachment works
