### ISSUE TITLE
What if I use cheat device on USB and hdd

### ISSUE THREAD

**Issue by Dokman** [root670/CheatDevicePS2#20]
If I use an HDD game will work too? Nor I have to put it at the usb?

**Comment by root670** [comment]
Any ELF file you launch from CheatDevice must be located on a flash drive or memory card. CheatDevice doesn’t support reading or writing anything from a hard drive, but if you’re running OPL from a CheatDevice to load a game from a hard drive that will work as long as the OPL ELF is located on a flash drive or memory card.
