### ISSUE TITLE
save manager does not recognize all Save

### ISSUE THREAD

**Issue by Wesleyjor6** [root670/CheatDevicePS2#21]
hello Wesley has a bug in the save manager he does not recognize all the saves I have some games that are saved on my memory card
when it does not recognize Save appears this symbol "?" Can you solve this bug?

**Comment by root670** [comment]
The question mark characters are used to replace non-ASCII characters in a save’s name. What do the titles appear as in the system browser menu?

**Comment by Wesleyjor6** [comment]
Do you have any social network to show the images I took?

**Comment by Wesleyjor6** [comment]
I really understand the question mark plus the save does not appear in the cheat device in the browser yes the save this good is not corrupted  were two games that cheat device did not recognize were the punisher and Scooby-Doo! Unmasked

**Comment by root670** [comment]
Please upload a screenshot of the save manage screen in CheatDevice and another screenshot showing how the save titles display in the system browser screen. You can drag the images directly onto the comment box on this page and it will automatically upload and embed it into your message.

**Comment by Wesleyjor6** [comment]
Unfortunately I'm using the cell phone but I'll leave the photos on MediaFire for you to download and view

https://www.mediafire.com/folder/oh14qt554g765/PS2

**Comment by root670** [comment]
Thanks for the images. I downloaded a few saves for The Punisher on GameFAQs and the save titles are displaying correctly in CheatDevice, so I am unable to recreate the issue.

Can you export the save to a flash drive from CheatDevice or another tool such as CodeBreaker and upload the *.cbs file? That way I can inspect the exact save you're using.

**Comment by Wesleyjor6** [comment]
Wesley the game punisher was saved right from the memory card I will try to back up the ulanchelf and then I will compact via zip then I will go through the cheat device to check if it recognizes

**Comment by Wesleyjor6** [comment]
here is the download link:https://mega.nz/#!7clVBIBJ!baz95O-coAIKONsUCGtK01NRnG_52dVYar0kN93SwXI

**Comment by root670** [comment]
I am unable to reproduce the bug using the files from that zip. I suspect there may be some abnormality in the file system that PS2SDK doesn't like.

By using [HD Project](http://www.ps2-home.com/forum/viewtopic.php?p=28560) you can create a binary image of your memory card, which should preserve any filesystem issues that may be present. If you run that tool to create a backup of your memory card, I'll be able to replicate your card locally and continue debugging.

One other thing to try is copying the save to another memory card using the browser screen, then see if Cheat Device still has trouble reading the title on the other card.

**Comment by Wesleyjor6** [comment]
eu descobri que meu cartão de memória não é original
