### ISSUE TITLE
Loading into opl after starting games

### ISSUE THREAD

**Issue by dwarfer78** [root670/CheatDevicePS2#27]
Hi I have ps2 phat and have backup lso's on an internal hard drive,  I have installed cheat device and when I start game after selecting cheats, my ps2 Loads to mcboot rather than straight into opl! I can still get cheats to work by going into ulaunch then launching opl from there, but I was hoping to to boot straight into opl! Is this possible? Cheers

**Comment by root670** [comment]
What is the contents of your `CheatDevicePS2.ini` file?

**Comment by dwarfer78** [comment]
hi thanks for replying
databaseReadOnly = CheatDatabase.zipdatabaseReadWrite =boot1 = mass: BOOT/BOOT.ELFboot2 = mass: BOOT/ESR.ELFboot3 =mc0: BOOT/BOOT.ELFboot4 = mc1:BOOT/ BOOT. ELFboot5 = rom:OSDYS
it is how you get it in the download

 
 
  On Sat, 23 May 2020 at 16:49, Wesley Castro<notifications@github.com> wrote:   


What is the contents of your CheatDevicePS2.ini file?

**Comment by dwarfer78** [comment]
Ok I am a bit of a noob at this but I have figured out what the problem was and now have it working perfectly!

**Comment by root670** [comment]
Glad it’s working for you now! What did the issue end up being?

**Comment by dwarfer78** [comment]
hi it was as simple as I hadn't got the path right for mc1 in the .ini file!  How stupid am I.

 
 
  On Sun, 24 May 2020 at 15:00, Wesley Castro<notifications@github.com> wrote:   


Glad it’s working for you now! What did the issue end up being?

**Comment by root670** [comment]
Happens to the best of us! I should add more error handling to detect issues like invalid paths.
