### ISSUE TITLE
support loading config and cheat DB from a DISC. add DVD-Video FS support and auto select cheats.

### ISSUE THREAD

**Issue by carl0sjt** [root670/CheatDevicePS2#31]
**Is your feature request related to a problem? Please describe.**
I would like to make a bootable disc with cheatdevice embedded in to the game disc. this allow fast booting and select of cheat patches wich enables Online gameplay on private servers: eg SaveMGO's Metal Gear Online from Metal Gear Solid 3 Subsistence.

**Describe the solution you'd like**
I would like to load the conf and db from cdrom with DVD-Vido file system support required for Free DVD Boot.

**Describe alternatives you've considered**

**Additional context**

**Comment by root670** [comment]
I'll probably add a FreeDVDBoot-derived version when that project stabilizes but it only supports a few console versions at the moment. I recommend checking out "PS2 Patch Engine" to embed cheats into an existing game image: https://www.ps2-home.com/forum/viewtopic.php?t=96
