### ISSUE TITLE
Please confirm...

### ISSUE THREAD

**Issue by Jay-Jay-OPL** [root670/CheatDevicePS2#4]
Hi, 

Someone with your username signed up on ps2-home.com today.  See post: http://www.ps2-home.com/forum/viewtopic.php?p=11687#p11687

Please confirm that this is you?  We just want to make sure it's not someone else doing a role play stunt.  Thanks in advance. :)

**Comment by root670** [comment]
Yes, that's me :-). Thanks for checking.
