### ISSUE TITLE
Multiple .txt-files in .zip-archive instead of one big .txt-file

### ISSUE THREAD

**Issue by Northrup69** [root670/CheatDevicePS2#42]
It would be awesome if the app had the function that you can put multiple .txt-files in a .zip-archive instead of just one big .txt-file.
It would be much easier and more manageable to add new cheats.

For example like this:

CheatsDatabase.zip
|   God of War (SCUS-973.99) [NTSC-U].txt
|   Grand Theft Auto - San Andreas (SLES-525.41) [PAL].txt
|   Final Fantasy X - Disc1 (SCUS-972.66) [NTSC-U].txt
|   Final Fantasy X - Disc2 (SCUS-972.69) [NTSC-U].txt
\  Final Fantasy X - Disc1 (SCUS-973.95) [NTSC-U].txt

instad of

CheatsDatabase.zip
\  CheatsDatabase.txt

**Comment by root670** [comment]
This is actually supported! If you use multiple txt files in the zip file as you described it should work.
