### ISSUE TITLE
Value-mapped cheats incompatibility with 4-type codes

### ISSUE THREAD

**Issue by re-bug** [root670/CheatDevicePS2#54]
The $ sign for value-mapped cheats is picked up as a comment, breaking 4-type cheats as well as 32-bit increment/decrement cheats, as one of their code lines begins with a value.

Codes of other types that make use of value-mapped cheats work correctly.

Example code:

"Kinetica (SCUS-97132)"
enable code
901ACF94 0C07076B

[weight]
40000000=2/275
41F00000=30/275
42F00000=120/275
43AF0000=350/275
442F0000=700/275
44BB8000=1500/275

vehicle weight
40780BC0 000900BF
$weight 00000000

**Expected behavior**

**Screenshots**

**Environment (please complete as much of the following information as possible):**
 - PS2 Region: PAL
 - PS2 Model Type: slim (SCPH-77004)
 - CheatDevice version: v1.7.5
 - Device CheatDevice is launched from: USB flash drive
 - Launch method: FMCB manually configured (L1) button shortcut
 - System modifications: FreeMcBoot
- `CheatDevicePS2.ini` contents:
```
[CheatDevicePS2]
databaseReadOnly = CheatDatabase.zip
databaseReadWrite = 
boot1 = mc1:BOOT/BOOT.ELF
boot2 = mc0:BOOT/BOOT.ELF
boot3 = mass:BOOT/BOOT.ELF
boot4 = mass:BOOT/ESR.ELF
boot5 = rom:OSDSYS
```

If there is a character that forces the software to pick a comment-like line as a code line, I didn't see it in the wiki.

**Comment by root670** [comment]
Value maps only work for what is typically the "value" portion of a code (the last 8 digits that follow the 8 digit address). The parsing code would need to be refactored to support multi-line codes where the typical "address" portion (first 8 digits) contains a value map reference.

**Comment by re-bug** [comment]
Oh, well, guess it's time to adapt the cheat then. Anyways, thanks for responding.
