### ISSUE TITLE
plaintext cheat databases support

### ISSUE THREAD

**Issue by eadmaster** [root670/CheatDevicePS2#6]
i'd like to suggest this feature to make the tool more user-friendly.

**Comment by root670** [comment]
This is already supported actually! The main README needs to be updated to reflect this, but cheats can be stored in .txt files.

**Comment by eadmaster** [comment]
thank you for implementing this, i've found [this was committed on 19-sep-2015](https://github.com/root670/CheatDevicePS2/commit/2c8a422a059d11a1446b9ee0f959c00b35c8a86c) while the latest release 1.2.1 was build before.
do you have a more recent build with TXT support working?
