### ISSUE TITLE
decrypting builtin cb10.cdb database

### ISSUE THREAD

**Issue by eadmaster** [root670/CheatDevicePS2#7]
i am trying to decrypt the builtin `cb10.cdb` database with [cb2util](https://github.com/mlafeldt/cb2util) but it fails:
```
>  cb2util.exe cheats -d cb10.cdb
cb10.cdb: invalid cheats file ID
```
any other method?

**Comment by root670** [comment]
CheatDevice uses a different format than CodeBreaker. cdb-util can be used to convert to/from CDB and TXT cheat files. https://github.com/root670/cdb-util/releases
